### ISSUE TITLE
QuarterlyGradingPermitInfo - 8DGT Watershed Not Translating Properly

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#15]
Steps to Reproduce:
Reporting Year = 2017
On Failure = Continue On Errors
Current User = KCI\Juanita.Miles

Upon running the Export to MDE the QuarterlyGradingPermitInfo table results in an Append_Failure. I feel like this may be due to the 8-digit watershed (WATERSHED8DGT) values not translating correctly.  

Source Data Watershed Values:
![image](https://user-images.githubusercontent.com/31770504/31396503-8caa3884-adb1-11e7-94b0-f2266fa93712.png)

MDE Export Watershed Values:
![image](https://user-images.githubusercontent.com/31770504/31396584-c454517a-adb1-11e7-9943-85fa0596a4b3.png)

All values appear to translate correctly with the exception of 02130904-Jones Falls. This value should appear as "Jones Falls" when exported. I've tried manually selecting the 02130904-Jones Falls value from the domain pick-list in the source data and running the export again, but the problem still occurs.

**Comment by gerrykelly** [comment]
This turned out to be a glitch in the code the processes the domains' values.  I think it is fixed.

I had thought the problem was going to be with the values mapping county domain codes to MDE's.  I think you will run into that case at some point (unless Lee gets some time to fix a couple things and I can followup).  There is a simple table in the database -- domains_baltco_mde_equivalency -- that supports the domains' codes conversion.  It should make sense when you look at it.  If you see a problem in the ETL where it looks like valid county codes are not being converted to the MDE value please check this table to see if it looks like it should work (and if you see an error for a county and/or MDE domain code-value when checking, feel free to edit the table to fix it)
