### ISSUE TITLE
AltBMPLines - Update Selection Set Logic for IMPL_STATUS?

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/balt_co_ETL#33]
Steps to Replicate:
Reporting Year: 2017
Continue on Errors: Yes
User Name: Juanita.Miles

While running the MDE export, an error is logged indicating: Domain field value conversion error in AltBMPLine: Failed to replace field value = Plan Revised (also for Unknown) in IMPL_STATUS.

Upon looking through issue #24 it appears that Stormwater features with an IMPL_STATUS of Plan Revised, Unknown, and Duplicate Record are not included in the selection set.

Please verify whether or not AltBMPLine features with an IMPL_STATUS = Plan Revised, Unknown, Duplicate Record should be excluded from the selection set as well. Excluding features with these status should eliminate the Domain field error, as this could be an issue that's causing an "append failure" of AltBMPLines.

**Comment by leeensminger** [comment]
@gerrykelly @JuanitaMiles Yes, the selection set for ALT_LINES should be updated so that these three status types do not go to MDE.

I think the current selection set is paraphrased as "all records where the REPORTING_YEAR is =< the user selected year.

So, the new, complete selection set needs to look like:

ALT_LINES feature class, where:
- REPORTING_YEAR <= user selected reporting year
- ALT_LINES.IMPL_STATUS = Complete OR Planning OR Under Construction OR Abandoned OR Design OR Removed [all domain values except Duplicate Record, Plan Revised, and Unknown]

In addition to Stormwater (#24 ), this will also apply to all other source entities where D_Impl_Status is used:
Inlet Cleaning #36 
Street Sweeping #37 
Impervious Removal #38 
Septic Systems #39

**Comment by gerrykelly** [comment]
good for test with next GP update

**Comment by JuanitaMiles** [comment]
selection set is working as it should
