### ISSUE TITLE
MDE export does not contain relationships

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#40]
The MDE export does not contain the explicit relationship classes found in the template.  Is it feasible to include this, or is there a reason why we could not achieve this?

**Comment by gerrykelly** [comment]
The relationship classes  were missing because of the way I needed to copy objects to avoid schema locking issues and I could not find a way around it.  Since you can't simply copy RCs from one GDB to another I needed to write a routine that loops through all the RCs in the MDE template, reads their properties then creates them in the output GDB (if one or both of the involved objects does not exist in the output -- as is the case on append failures -- then you will get a message that the RC could not be created.
Test after my next GP service update.

**Comment by BC89** [comment]
Can't we simply put the relationship classes in the templates db and be done with it?



Sent from my Samsung Galaxy , an AT&T LTE smartphone


-------- Original message --------

**Comment by gerrykelly** [comment]
@BC89 @leeensminger 
With how the ETL works now, I think I need to use the routine I wrote yesterday and it works fine (but let's verify).

**Comment by leeensminger** [comment]
@gerrykelly where did we leave off with this?  are relationships to be expected in the output?  they are not currently.

**Comment by gerrykelly** [comment]
@leeensminger 
This should be working but I had deactivated the code for testing and forgot to put it back in (the all-messages log file from your runs have had a message "skipping relationship classes RESTORE later" in it -- as a reminder to me)

**Comment by leeensminger** [comment]
Appears OK
