### ISSUE TITLE
Stormwater - Selection Set 1A - migrated records also show up in append_failure

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#60]
See ETL output file: \\vm-wsscmta\export\MDE_2018_01_29_15_56.zip

The BMP table contains 710 records.  All 710 records are also found in the Append_Failure_BMP_p_to_BMP table.  If I understand correctly, records should be in one or the other, but not both.

Note that the 710 records are not quite correct in terms of the selection set, but keeping that issue separate and unique for now.

**Comment by gerrykelly** [comment]
@leeensminger 
This was because even though the append failed, 710 records were written to the table anyway.  I thought it would be all or nothing.  That not being the case I have added code to delete all the records from a target table anytime the append fails in the several ways it can (I can see that being an issue though if more than one source date table is to be appended to the MDE target and one is successful but the rows are later deleted due to a subsequent failure.  But, I think that is OK bc the idea is that you keep fixing things until it all works, then that issue becomes a moot point)

**Comment by gerrykelly** [comment]
@leeensminger 
with our current data for testing, the append is not failing.  If you want to test that it is fixed, you could edit something to intentionally make it fail, but like I said in my comment a few week ago it's kind of a moot point since the goal is to make the append successful and once it is there is no problem.

**Comment by leeensminger** [comment]
Looks ok
