### ISSUE TITLE
Stormwater - BMP Inspections - Selection Set 1C ghosted BMP inspections are being migrated

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#68]
This is  discussed in the first comment of #67 :
_Also - target BMPInspections are related to BMPs. And the BMPInspections table includes inspections for these Archived records - they have an BMP_ID, and interestingly, because the BMP table records are not present, these inspections are orphaned. The inspections should not be loaded to target either._

Archived records are being inadvertently migrated to BMPPOI, but shouldn't be, based on SW_TRACKING.TRACKING_STATUS.  The inspections related to these facilities are also being loaded to BMPInspections, and shouldn't be.

**Comment by gerrykelly** [comment]
@leeensminger 
I thought other bug fixes would have resolved this, but I get 3 BMPInspections inspections records when I use RY 2010.  I'm going to ignore that for now and circle back and try to figure it out later if lt's a real problem and matters.

**Comment by leeensminger** [comment]
@gerrykelly I think its an issue, yes - running RY 2014 again (selection set 1A) gives me all the correct inspections for 1A, plus 9 inspections related to 1C.

These are the 9 bad records that were loaded, and shouldn't have been:
![image](https://user-images.githubusercontent.com/4103847/36817724-3d2b52de-1cb0-11e8-89ec-f4cc35be41a4.png)

**Comment by gerrykelly** [comment]
@leeensminger 
I never seem to get quite the same results as you, but I see the problem of the orphaned inspections.  Rather than spending even more time going around in circles to find the cause, I just put in a last-step routine that deletes the orphans.  I thought there was still a glitch with having more inspection records than related BMPs, but from a data perspective it looks legit with BMPs sometimes having more than one related inspection on the latest inspection date:
![image](https://user-images.githubusercontent.com/8259136/36872110-24b99284-1d72-11e8-9571-f919eb905aa7.png)

**Comment by leeensminger** [comment]
Resolved
