### ISSUE TITLE
Selection set 1C - some records have "orphan" output BMP.BMPPOI values

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#71]
About half of the values in BMP.BMPPOI = "orphan".  These are valid records and should have a valid BMPPOI.  I haven't figured out the pattern for these yet, and why only some of these are coming through as orphaned.

![image](https://user-images.githubusercontent.com/4103847/36637475-78f1a9f2-19aa-11e8-91ef-d6df3c8dbffd.png)

**Comment by gerrykelly** [comment]
@leeensminger 
The "about half" being wrongly orphaned was bc querying back to the sw_tracking records it was random which one of the 2 records related to a BMP was being used.  So that should be fixed, but was a complicated pain.  For RY 2023 that left one orphan -- probably related to that conversion of a conversion nuance or the one Part C sw_tracking  records that did not have a 2nd related record.

**Comment by leeensminger** [comment]
Appears resolved
