### ISSUE TITLE
AltBMPPoly - Reforestation - Planting Type domain translations are not correct

### ISSUE THREAD

**Issue by leeensminger** [kcigeospatial/balt_co_ETL#74]
The TREE_AREAS.PLANTING_TYPE values are not being converted correctly.  All values are being migrated as "FPU"... I think this was the documentation some time ago - based upon the issue linked below, it sounds like the appropriate domain translations were made?  But they are not currently coming through in the KCI dev ETL. 

https://github.com/kcigeospatial/balt_co_npdes/issues/288

I will update in balt_co_npdes when appropriate.

**Comment by gerrykelly** [comment]
@leeensminger 
This seemed like a little issue but was actually a significant change to the routine bc of how the tree areas/infos are specifically handled.  After getting the ALTBMP_TYPE to calc, settled on adding it as a dissolve field for when the feature class is dissolved after the areas>info join.  All this and I think the only result is that there a 3 values in the D_TR_Planting_Type domain and now two of them map to FB instead of FPU
![image](https://user-images.githubusercontent.com/8259136/36647396-0b7e3a4e-1a53-11e8-9323-c542c7f077d6.png)

**Comment by leeensminger** [comment]
Appears resolved
